### PR TITLE
Plugin adjusted to met a new requirements from Composer 2.0

### PR DESCRIPTION
**Pull request by alroniks**
As Composer 2.0 is coming soon, they introduce changes in their plugins API, and these changes adjust the code to be compatible with the second version or composer plugins API.

Upgrade was done accordingly to this guide https://github.com/composer/composer/issues/8726

### CODE REVIEW

**Comment by boajer** [comment]
I've tested this plugin with composer v1 and v2 and  installed https://github.com/oat-sa/generis/pull/771 as the only extension. It works.

**Comment by gitromba** [comment]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Comment by gitromba** [comment]
Same - successful - results when testing locally https://github.com/oat-sa/generis/pull/771.

**Review by gitromba — COMMENTED** [review]
What is your plan with the release @Alroniks? Will you bump the major version?

**Comment by alroniks** [comment]
@gitromba I don't think that we have to bump the major version, minor will be enough because it does not break any backward compatibility but brings compatibility with the new version of Composer. As it simple PHP library, we don't have to set a version somewhere in the code, one thing that should be done just draft release after merging a pull request.
Also, in code, we require this library as `~1.1||dev-master` that means it will take updates from the branch.

**Pull request merged**
